name: nginx
base: core22
version: '1.22.0'
summary: Web server, reverse proxy, load balancer
description: |
  Web server that can be used as a reverse proxy, load balancer, mail proxy, and HTTP cache
grade: devel
confinement: strict
apps:
  nginx:
    command: bin/nginx -p $SNAP_DATA -e stderr
    reload-command: bin/nginx -p $SNAP_DATA -e stderr -s reload
    stop-command: bin/nginx -p $SNAP_DATA -e stderr -s quit
    daemon: forking
    install-mode: disable
    plugs:
      - network-bind
  testconf:
    command: bin/nginx -p $SNAP_DATA -e stderr -t
slots:
  servfiles:
    interface: content
    content: servfiles
    write:
      - $SNAP_DATA/html
parts:
  nginx:
    plugin: autotools
    source: https://nginx.org/download/nginx-1.22.0.tar.gz
    autotools-configure-parameters:
      - --prefix=/
      - --sbin-path=/bin/nginx
      - --user=root
      - --group=root
      - --with-file-aio
      - --with-http_addition_module
      - --with-http_auth_request_module
      - --with-http_dav_module
      - --with-http_degradation_module
      - --with-http_flv_module
      - --with-http_geoip_module
      - --with-http_gunzip_module
      - --with-http_gzip_static_module
      - --with-http_mp4_module
      - --with-http_realip_module
      - --with-http_secure_link_module
      - --with-http_slice_module
      - --with-http_ssl_module
      - --with-http_stub_status_module
      - --with-http_sub_module
      - --with-http_v2_module
      - --with-mail
      - --with-mail_ssl_module
      - --with-pcre-jit
      - --with-stream
      - --with-stream_geoip_module
      - --with-stream_realip_module
      - --with-stream_ssl_module
      - --with-stream_ssl_preread_module
      - --with-threads
    build-packages:
      - build-essential
      - libpcre2-dev
      - libpcre3-dev
      - zlib1g-dev
      - libssl-dev
      - libcrypt-dev
      - libgeoip-dev
      - libmhash-dev
      - libperl-dev
      - libxslt1-dev
    stage-packages:
      - libgeoip1
    stage:
      - -conf/nginx.conf
      - -html
  conf:
    plugin: dump
    source: conf
    organize:
      '*': conf/
  html:
    plugin: dump
    source: html
    organize:
      '*': html/


