name: nginx
base: core22
version: '1.22.0'
summary: Web server, reverse proxy, load balancer
description: |
  Web server that can be used as a reverse proxy, load balancer, mail proxy, and HTTP cache
grade: devel
confinement: strict
apps:
  nginx:
    command: usr/bin/nginx
    daemon: forking
    install-mode: disable
    plugs:
      - network-bind
layout:
  /etc/nginx:
    bind: $SNAP_DATA/conf
  /var/log/nginx:
    bind: $SNAP_DATA/log
  /var/lib/nginx:
    bind: $SNAP_DATA/var
  /var/www:
    bind: $SNAP_COMMON/www
parts:
  nginx:
    plugin: autotools
    source: https://nginx.org/download/nginx-1.22.0.tar.gz
    autotools-configure-parameters:
      - --prefix=/etc/nginx
      - --sbin-path=/usr/bin/nginx
      - --conf-path=/etc/nginx/nginx.conf
      - --error-log-path=/var/log/nginx/error.log
      - --pid-path=/var/lib/nginx/nginx.pid
      - --lock-path=/var/lib/nginx/nginx.lock
      - --http-log-path=/var/log/nginx/access.log
      - --http-client-body-temp-path=/var/lib/nginx/client-body
      - --http-proxy-temp-path=/var/lib/nginx/proxy
      - --http-fastcgi-temp-path=/var/lib/nginx/fastcgi
      - --http-scgi-temp-path=/var/lib/nginx/scgi
      - --http-uwsgi-temp-path=/var/lib/nginx/uwsgi
      - --user=root
      - --group=root
    build-packages:
      - build-essential
      - libpcre2-dev
      - libpcre3-dev
      - zlib1g-dev
      - libssl-dev
      - libcrypt-dev
      - libgeoip-dev
      - libmhash-dev
      - libperl-dev
      - libxslt1-dev
    stage-packages:
      - libpcre2-16-0
      - libpcre2-32-0
      - libpcre3
      - libpcre32-3
      - libgeoip1

