name: nginx
base: core22
version: '1.22.0'
summary: Web server, reverse proxy, load balancer
description: |
  Web server that can be used as a reverse proxy, load balancer, mail proxy, and HTTP cache
grade: devel
confinement: strict
apps:
  nginx:
    command: bin/nginx -p $SNAP_DATA -e stderr
    reload-command: bin/nginx -p $SNAP_DATA -e stderr -s reload
    stop-command: bin/nginx -p $SNAP_DATA -e stderr -s quit
    daemon: forking
    install-mode: disable
    plugs:
      - network-bind
  testconf:
    command: bin/nginx -p $SNAP_DATA -e stderr -t
parts:
  nginx:
    plugin: autotools
    source: https://nginx.org/download/nginx-1.22.0.tar.gz
    autotools-configure-parameters:
      - --prefix=/
      - --sbin-path=/bin/nginx
      - --user=root
      - --group=root
    build-packages:
      - build-essential
      - libpcre2-dev
      - libpcre3-dev
      - zlib1g-dev
      - libssl-dev
      - libcrypt-dev
      - libgeoip-dev
      - libmhash-dev
      - libperl-dev
      - libxslt1-dev
    stage-packages:
      - libgeoip1

